### ISSUE TITLE
onSelect property not working 

### ISSUE THREAD

**Issue by BhumiSukhadiya** [freeranger/react-bootstrap-tabs#2]
I am using Tabs with react and redux but onSelect doesn't work.
I am displaying data dynamically from redux store in each tabs.
The tab data changes after double click on Tabs Header.
Is there any solution for this?

**Comment by freeranger** [comment]
Hi
If you look at the demo site: https://freeranger.github.io/react-bootstrap-tabs-demo/
and open the developer console then you will see log messages for the "Multiple Tabs, selected by index" and "Multiple Tabs, selected by label" examples - these are using onSelect.
The code for the demo is here: https://github.com/freeranger/react-bootstrap-tabs-demo/blob/master/app/App.js

If you can't figure it out from there then please post a link to a minimal repo showing the problem you are having.

**Comment by BhumiSukhadiya** [comment]
I am having isuue on tabComponent route in my project.
The problem is that if i am clicking another tab once then it shows the default tab's data first and then if i click on that tab one more time then it will shows the original data.
Here is the link for repo: https://github.com/BhumiSukhadiya/React_Project_Repo

![screenshot 6](https://cloud.githubusercontent.com/assets/26542624/26189484/9adab340-3bc2-11e7-8422-1bbc11c6b3ac.png)

**Comment by freeranger** [comment]
I can't get your app to build in my environment - you need to post a link to a *minimal* working example showing the problem
You could take my demo app as a starting point and wire up the tabs how you have them in your app and see if they work for you.
Your code has too many moving parts that could be an issue - you have the tabs inside a custom component component with routes going on and other libraries/components - strip them all away and start with the basic tabs and see if they work (since they do in my demo app, I am guessing they will) and then add on the other bits one at a time and see when they break...

**Comment by freeranger** [comment]
I just pasted the basics of your tabs into my demo app:
```javascript
 function onTabSelect(index)  {
     console.log(index);
  };
```
```html
    <div className="root">
        <div className="container">
          <Tabs onSelect={onTabSelect}>
            <Tab label="Tab1">
              <div className="row">
                  hello
              </div>
            </Tab>
            <Tab label="Tab2">
              <div className="row">
                tab3
              </div>
            </Tab>
            <Tab label="Tab3">
              <div className="row">
                tab3
              </div>
            </Tab>
            <Tab label="Tab4">
              <div className="row">
                tab4
              </div>
            </Tab>
            <Tab label="Tab5">
              <div className="row">
                tab5
              </div>
            </Tab>
          </Tabs>
        </div>
    </div>
```
and clicked on each tab and got the onclick message and the right content:
![image](https://cloud.githubusercontent.com/assets/1401069/26191050/39fef266-3ba4-11e7-8c68-8bb0cfd3f95e.png)
which suggests that whatever your problem is, it isn't the tabs component - something else is going on there.
At a guess I'd say you aren't setting the selected tab when your TabComponent renders, so when you change tabs and cause a re-render, what tab is going to be rendered?  Since you haven't set the `selected` property on the `<Tabs>` component then the default tab will be selected again.

**Comment by BhumiSukhadiya** [comment]
When i am using it with dynamic data it doesn't work properly.
I have implemented it in small repo.Just take a look and let me know that where i am wrong?
LINK: https://github.com/BhumiSukhadiya/rbt_demo.git

**Comment by freeranger** [comment]
This does not work for me
```
    let jsonObj = [];
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```
As I said, please post a link to a *minmal* example demonstrating the problem - you don't need a node server running in a minimal example.  Take the demo app as a starting point and add as *little* as possible to that to demonstrate the problem.
There should be no need for yarn
There should be no need for any server side code
There should be no need for authorisation headers
There should be no need for panel controls
There should even be no need to have your own custom component wrapping the tabs component

**Comment by freeranger** [comment]
Closing due to no response from the reporter and cannot recreate and cannot get the reporter's overly complex example running
