### ISSUE TITLE
Hi, I'm facing design issue in mobile version when tab is disabled it hides the text but not the "<li>" parent tag.

### ISSUE THREAD

**Issue by PathFinder5196** [freeranger/react-bootstrap-tabs#4]
I've tried applying "style" tag to <Tab> as well but that also seem not to be working.

**Comment by freeranger** [comment]
Hi,
I don’t know what “mobile version” you mean - there aren’t different versions of this component for mobile or not mobile.

Can you please post a link to a minimal working solution that demonstrates the problem you are having.

Thanks

**Comment by PathFinder5196** [comment]
Hi,

I meant to say responsive website.
Please find screenshot for reference.

**Comment by freeranger** [comment]
Hi,

The screenshot doesnt help really I’m afraid - please post a link to a minimal working site that demonstrates the problem.  You could, for example, fork my demo site as a starting point and recreate the issue in your fork: https://github.com/freeranger/react-bootstrap-tabs-demo

**Comment by PathFinder5196** [comment]
Hi,

You can refer below code.

https://github.com/PathFinder5196/react-bootstrap-tabs-demo/tree/PathFinder5196-style-issue

**Comment by PathFinder5196** [comment]
@freeranger I'm looking for some guide, If you can reach me at https://twitter.com/lavesh_katariya. It will be great help.

**Comment by freeranger** [comment]
The style property is a react property, not a html property, so you have to supply values the react way - so `style={{display:"none"}}` instead of `style="display:none"`

You can find examples of this in the tests: 
https://github.com/freeranger/react-bootstrap-tabs/blob/master/src/tests/index.js 
and in the demo site: 
https://github.com/freeranger/react-bootstrap-tabs-demo/blob/master/app/App.js
